sudo: required
language: python

services:
  - docker
before_install:
  - docker build -t lukasheinrich/quickana-tutorial-ath .
script:
  - docker run -it lukasheinrich/quickana-tutorial-ath ./tests/runtest.sh
